FROM maven:3.5.0-jdk-8-alpine as build

RUN mkdir -p /home/app
WORKDIR /home/app
COPY pom.xml /home/app
RUN mvn dependency:go-offline
COPY ./src/ /home/app/src/
RUN mvn package -DskipTests


FROM openjdk:8-jre-alpine
COPY --from=build  /home/app/target/*.jar /usr/local/lib/app.jar
ENTRYPOINT ["java","-jar","-Dspring.profiles.active=dev","/usr/local/lib/app.jar"]